### ISSUE TITLE
Query on Embedding_tutorial.ipynb output

### ISSUE THREAD

**Issue by vivek-ksingh** [HantaoShu/DeepSEM#12]
Hi DeepSEM team,

I am trying to understand the output from Embedding_tutorial.ipynb

My understanding is that after running the 'embedding' task, I should get a AnnData of the shape: 

n_samples x n_hidden 
where,
n_samples=no. of samples in my input data, and 
n_hidden=opt.n_hidden specified by me in main.py settings

therefore, implying that my input data has been embedded into a lower dimensional (=n_hidden) space.

However, the dimension I am getting in the output is:
n_samples x n_genes
where, n_genes=no. of genes in my input data

This implies that I am not getting a lower-dimensional embedding that I am looking for.

Can you please explain if I am missing something here?

Thanks,
Vivek

**Comment by HantaoShu** [comment]
The output of deesem is no_sample*no_gene as we assume deepsem can denoise the sc data. we use pca on the output of deepsem. More details can be found in our paper.

**Comment by vivek-ksingh** [comment]
Thank you. This is helpful.

One follow-up question:
Is there a way to get the n_samples x n_hidden matrix also if I wish to have a lower-dimensional embedding of my input data?

Thanks,
Vivek

**Comment by HantaoShu** [comment]
We can not directly get n_samples x n_hidde matrix from DeepSEM. You can use PCA on the output of DeepSEM instead.

**Comment by vivek-ksingh** [comment]
Thanks for the clarification.

Best,
Vivek
