### ISSUE TITLE
BEELINE integration question

### ISSUE THREAD

**Issue by yutuyt01** [HantaoShu/DeepSEM#15]
Greetings!

Thank you for using BEELINE in your study. I was wondering if the DeepSEM team integrated the algorithm into BEELINE's pipeline or just used the datasets to benchmark. If the former, do you all still have the scripts for your benchmarking? I'd like to implement DeepSEM as a benchmarkable algorithm in BEELINE.

Thanks,
Tim

**Comment by HantaoShu** [comment]
The former， please refer beeline benchmark repo generateExpInputs.py file

**Comment by yutuyt01** [comment]
Thank you for the response - apologies, I don't think I phrased my question properly. Do you have files such as deepSEMrunner.py and the corresponding Dockerfile that BEELINE requires? If so, could these be added in a pull request to BEELINE's repo?

Thanks a bunch,
Tim

**Comment by HantaoShu** [comment]
sorry, no such file.
