### ISSUE TITLE
About input data format

### ISSUE THREAD

**Issue by wangtianqi1993** [HantaoShu/DeepSEM#7]
hello, i find that the demo input data format is gene as column,  that is different from the instructions on the home page about input data format. can you tell me what is right, thank you~~~

**Comment by HantaoShu** [comment]
The data format is genes as columns and cells as rows. Sorry for the misunderstanding. I have updated the readme file.

**Comment by wangtianqi1993** [comment]
> 

OK，thank you
i also want to ask about the GRN layer，GRN layer is only the model layer？it auto learned from train process ，we not need input raw GRN data set，so I don't understand how to show the role of GRN layer. Can you explain it to me, thank you.

**Comment by HantaoShu** [comment]
GRNlayer is one layer that auto learn GRN from given expression data. We do not need to input GRN. Maybe input raw grn as initialization can help training but we didn' try this. GRNlayer is designed from sem model and details about our model are shown is our paper.  Any other questions are welcome.
