### ISSUE TITLE
Issue with pandas DataFrame constructor

### ISSUE THREAD

**Issue by jelkhouryy** [HantaoShu/DeepSEM#8]
Hello! I get the following issue when trying to run the embedding tutorial, any idea what the problem is ?
Thanks! 

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/102976031/164204894-60471709-b887-4721-a75a-c6f8fb7cc79f.png">

**Comment by HantaoShu** [comment]
Sorry for this error. Please used Zeisel_dataset.X instead Zeisel_dataset in last line,  pd.DataFrame(Zeisel_dataset.X,index=....)

**Comment by jelkhouryy** [comment]
Thanks a lot!
